spring:
  application:
    name: eureka-server
server:
  port: 1112
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/
    register-with-eureka: true #高可用注册中心
    fetch-registry: true #高可用注册中心