spring:
  application:
    name: gateway5555
  security:
    user:
      name: admin
      password: admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mld8001?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    filters: stat,wall,log4j
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
server:
  port: 5555
zuul:
  routes:
    api-a:
      path: /api-a/**/**
      serviceId: sysuser8020
    api-b:
      path: /api-b/**
      serviceId: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/