spring:
  application:
    name: feign-consumer
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://peer1:1111/eureka/,http://peer2:1112/eureka/