server:
  port: 8011
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mld8001?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    filters: stat,wall,log4j
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: dept8010
  security:
    user:
      name: admin
      password: admin
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.fangyou.entity
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/